# POSTTEST 7 KB
## LIDYA SIMANUNGKALIT
## 2009106125
## KB C1 20


# TENSORFLOW  BASIC

In [1]:
import pandas as pd
import numpy as np  
import matplotlib.pyplot as plt
import tensorflow as tf

# 1. SHAPE (5,5) RANDOM

In [2]:
random_tensor = tf.random.normal([5,5],mean=2)

random_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1.2230608 , 2.31855   , 2.957589  , 1.3531401 , 0.92784667],
       [2.3567889 , 0.4127922 , 2.9725502 , 3.788623  , 1.8052181 ],
       [3.19646   , 0.24205375, 2.7794914 , 2.911897  , 1.4793952 ],
       [1.8638815 , 0.68177426, 0.31586993, 3.3206081 , 0.08094513],
       [2.7847548 , 3.300223  , 1.5507061 , 0.53502357, 2.3440251 ]],
      dtype=float32)>

# 2. SHAPE (5,5) LIST BILANGAN PRIMA

In [5]:
prime_tensor=tf.constant ([[2,3,5,7,11],[13,17,19,23,29],[31,37,41,43,47],[53,59,61,67,71],[73,79,83,89,97]],dtype=tf.float32)

print(prime_tensor)

tf.Tensor(
[[ 2.  3.  5.  7. 11.]
 [13. 17. 19. 23. 29.]
 [31. 37. 41. 43. 47.]
 [53. 59. 61. 67. 71.]
 [73. 79. 83. 89. 97.]], shape=(5, 5), dtype=float32)


# 3. MENAMPILKAN DIMENSI

### VARIABEL RANDOM TENSOR

In [15]:

random_tensor.get_shape()

TensorShape([5, 5])

### VARIABEL PRIME_TENSOR

In [16]:
tf.shape(prime_tensor).numpy()

array([5, 5])

# 4. PERHITUNGAN ARITMETIKA

## penjumlahan

In [17]:
print(tf.add(random_tensor, prime_tensor))

tf.Tensor(
[[ 3.2230608  5.31855    7.957589   8.35314   11.927847 ]
 [15.356789  17.412792  21.97255   26.788624  30.805218 ]
 [34.19646   37.242054  43.77949   45.911896  48.479397 ]
 [54.86388   59.681774  61.31587   70.32061   71.08095  ]
 [75.78475   82.300224  84.550705  89.53503   99.344025 ]], shape=(5, 5), dtype=float32)


## pengurangan

In [18]:
print(tf.subtract(random_tensor, prime_tensor))

tf.Tensor(
[[ -0.77693915  -0.6814499   -2.042411    -5.64686    -10.072153  ]
 [-10.643211   -16.587208   -16.02745    -19.211376   -27.194782  ]
 [-27.80354    -36.757946   -38.22051    -40.088104   -45.520603  ]
 [-51.13612    -58.318226   -60.68413    -63.67939    -70.91905   ]
 [-70.21525    -75.699776   -81.449295   -88.46497    -94.655975  ]], shape=(5, 5), dtype=float32)


## perkalian

In [19]:
print(tf.multiply(random_tensor, prime_tensor))

tf.Tensor(
[[  2.4461217   6.9556503  14.787945    9.471981   10.206313 ]
 [ 30.638256    7.0174675  56.478455   87.13833    52.351326 ]
 [ 99.09026     8.955989  113.95915   125.21157    69.53157  ]
 [ 98.78572    40.22468    19.268066  222.48074     5.7471046]
 [203.2871    260.71762   128.7086     47.617096  227.37044  ]], shape=(5, 5), dtype=float32)


## pembagian

In [20]:
print(tf.divide(random_tensor, prime_tensor))

tf.Tensor(
[[0.6115304  0.77285004 0.5915178  0.19330573 0.0843497 ]
 [0.18129145 0.02428189 0.15645    0.16472274 0.0622489 ]
 [0.10311161 0.00654199 0.06779248 0.06771854 0.03147649]
 [0.03516757 0.0115555  0.0051782  0.04956131 0.00114007]
 [0.03814733 0.04177498 0.01868321 0.0060115  0.02416521]], shape=(5, 5), dtype=float32)


## perpangkatan

In [21]:
print(tf.pow(random_tensor, prime_tensor))

tf.Tensor(
[[1.4958779e+00 1.2463771e+01 2.2630234e+02 8.3061428e+00 4.3877143e-01]
 [6.9210000e+04 2.9338324e-07 9.7601082e+08 2.0187022e+13 2.7501774e+07]
 [4.4131382e+15 1.6022748e-23 1.5943324e+18 9.1110415e+19 9.8618176e+07]
 [2.1486685e+14 1.5303663e-10 2.9512441e-31 8.3479734e+34 0.0000000e+00]
 [2.9474581e+32           inf 6.5155223e+15 6.6863550e-25 7.6973218e+35]], shape=(5, 5), dtype=float32)


## logaritma

In [22]:
print(tf.math.log(random_tensor, prime_tensor))

tf.Tensor(
[[ 0.20135659  0.840942    1.0843744   0.3024279  -0.07488878]
 [ 0.85730004 -0.8848109   1.0894202   1.3320026   0.59068143]
 [ 1.1620439  -1.4185954   1.0222679   1.0688047   0.3916333 ]
 [ 0.6226611  -0.3830567  -1.1524248   1.200148   -2.5139837 ]
 [ 1.0241598   1.1939901   0.43871042 -0.6254445   0.8518696 ]], shape=(5, 5), dtype=float32)


# 6. NILAI MAX-MIN VARIABEL random_tensor

## MAKSIMUM

In [25]:
maxkolom = tf.argmax(random_tensor, axis=0)
maxbaris = tf.argmax(random_tensor, axis=1)
print("Nilai maximum berdasarkan kolom:",maxkolom.numpy())
print("Nilai maximum berdasarkan baris:",maxbaris.numpy())

Nilai maximum berdasarkan kolom: [2 4 1 1 4]
Nilai maximum berdasarkan baris: [2 3 0 3 1]


## MINIMUM

In [26]:
minkolom = tf.argmin(random_tensor, axis=0)
minbaris = tf.argmin(random_tensor, axis=1)
print("Nilai minimum berdasarkan kolom:",minkolom.numpy())
print("Nilai minimum berdasarkan baris:",minbaris.numpy())

Nilai minimum berdasarkan kolom: [0 2 3 4 3]
Nilai minimum berdasarkan baris: [4 1 1 4 3]


# 7. PENGGABUNGAN random_tensor & prime_tensor MENGGUNAKAN
#     CONCENATION


In [32]:
concat_rt = (random_tensor)
concat_pt = (prime_tensor)
print("sizes original data:",concat_rt.shape,concat_pt.shape)
concat_rt = tf.concat([concat_rt,concat_pt],axis=0)
print("size  data yang sudah  concenation:",concat_rt.shape)

sizes of the original data: (5, 5) (5, 5)
size  data yang sudah  concenation: (10, 5)


# 8. SORTING
### random tensor

In [50]:
sorting = tf.sort(random_tensor, direction="DESCENDING")
print('urutan random_tensor  secara descending :')
print(sorting)


urutan random_tensor  secara descending :
tf.Tensor(
[[2.957589   2.31855    1.3531401  1.2230608  0.92784667]
 [3.788623   2.9725502  2.3567889  1.8052181  0.4127922 ]
 [3.19646    2.911897   2.7794914  1.4793952  0.24205375]
 [3.3206081  1.8638815  0.68177426 0.31586993 0.08094513]
 [3.300223   2.7847548  2.3440251  1.5507061  0.53502357]], shape=(5, 5), dtype=float32)


### prime_tensor

In [53]:
sorting = tf.sort(prime_tensor, direction="DESCENDING")
print('urutan prime_tensor  secara descending :')
print(sorting)


urutan prime_tensor  secara descending :
tf.Tensor(
[[11.  7.  5.  3.  2.]
 [29. 23. 19. 17. 13.]
 [47. 43. 41. 37. 31.]
 [71. 67. 61. 59. 53.]
 [97. 89. 83. 79. 73.]], shape=(5, 5), dtype=float32)
